# Generated by Django 3.2.16 on 2023-01-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('roll', models.IntegerField()),
                ('age', models.IntegerField()),
                ('profile', models.TextField()),
                ('data_enrolled', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
